### ISSUE TITLE
Create new table definitions

### ISSUE THREAD

**Issue by micah-prime** [SnowEx/snowexsql#104]
Let's create all the new table definitions as outlined in the re-organization diagram

Tables to create are

- [x] instruments @micah-prime 
- [x] observers @micah-prime 
- [x] #133 
- [x] #134
- [x] sites
- [x] campaigns @jtmaze 

Each table can have it's own file (like @jomey 's reorg)

Tables to update are:
- [x] #132 
- [x] #136

Also linking to a discussion around observers
#137

![IMG_2841](https://github.com/user-attachments/assets/c14470aa-7d50-473e-b2a7-213629578751)

**Comment by micah-prime** [comment]
These are being pushed to the `dev` branch, so PRs can be made there

**Comment by jomey** [comment]
Noting that we should also add some indexes on the foreign key columns.
One example on how to do this:
```python
name = Column(String, index=True)
```

**Comment by jomey** [comment]
Other definition to consider is to require the presence of an attribute/column via `NOT NULL`
```python
name = Column(String, nullable=False)
```
https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Column.params.nullable

**Comment by jomey** [comment]
Saving a reference on why we don't need to set limits on `varchar`
https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_varchar.28n.29_by_default
