### ISSUE TITLE
Restructure work - clear up site conditions vs site location

### ISSUE THREAD

**Issue by micah-prime** [SnowEx/snowexsql#127]
We now have a `Site` belonging to a `Campaign`. Previously `SiteData` had a date AND location associated with weather, conditions, etc.

To maintain this info, we can change `SiteData` to `SiteConditions` and link that to the `Site`.  

https://github.com/SnowEx/snowexsql/blob/dev/snowexsql/tables/site_data.py#L11
https://github.com/SnowEx/snowexsql/blob/dev/snowexsql/tables/site.py#L20

`Site` can have the location and `SiteConditions` can have date-specific conditions. Each point or pit can link to a `SiteCondition`, belonging to a `Site`, belonging to a `Campaign`.

FYI @micahjohnson150

**Comment by jomey** [comment]
```mermaid
classDiagram
  Campaign <|-- Sites
  Sites <|-- SiteCondition
  class Campaign{
    +int id
  }
  class Sites{
    +int id
    +int campaign_id
    +int site_condition_id
  }
  class SiteCondition{
    +int
  }
```

**Comment by jomey** [comment]
I imagine all of these pit header fields going into the `Site` table

![image](https://github.com/user-attachments/assets/996728db-41f8-4917-a83f-e26689b6489c)

**Comment by micah-prime** [comment]
> I imagine all of these pit header fields going into the `Site` table
> 
> ![image](https://private-user-images.githubusercontent.com/178649/369055901-996728db-41f8-4917-a83f-e26689b6489c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Nzc2NzYsIm5iZiI6MTcyNjc3NzM3NiwicGF0aCI6Ii8xNzg2NDkvMzY5MDU1OTAxLTk5NjcyOGRiLTQxZjgtNDkxNy1hODNmLWUyNjY4OWI2NDg5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQyMDIyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGVlNjM5NzViNzBjNjMxZjNkOWI2ZmZjZDQzZjhlZTBhZjIyYTE2OTQ2YWU5NTIzY2IyNzU5OTE5NTMzNDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BplCic2Q8UKSSbdcVD0FLabVcGMZAbtAcpt6oDp3jEM)

Yep, basically everything here https://github.com/SnowEx/snowexsql/blob/master/snowexsql/tables/site_data.py#L15-L28

**Comment by micah-prime** [comment]
So I was initially under the impression that a site would not be date dependent unlike the pits. This was a misconception on my part.
Since Site == a pit, does it still make sense to split up the site condition into a separate table, or should we just keep the site conditions in the Site table?
@jomey

**Comment by jomey** [comment]
> So I was initially under the impression that a site would not be date dependent unlike the pits. This was a misconception on my part. Since Site == a pit, does it still make sense to split up the site condition into a separate table, or should we just keep the site conditions in the Site table? @jomey

I guess we can keep these as attributes in the table. Can't think of a obvious reason and we can come back to this if needed.
Think the [overview here](https://github.com/SnowEx/snowexsql/issues/137#issuecomment-2363913938) seems to be the target for now.

**Comment by micah-prime** [comment]
Sweet, I'll just consolidate for now then
