### ISSUE TITLE
Restructure - measurement type table

### ISSUE THREAD

**Issue by micah-prime** [SnowEx/snowexsql#134]
Create and link a measurement type table

**Comment by jomey** [comment]
From my perspective, the Measurement_Type table should have these columns:
`ID, name, unit, composite(bool)`

Then we could have entries like this:
| ID | Name | Unit | Derived |
|-|-|-|-|
| 1 | SWE | mm | |
| 2 | SWE | 50 m | |
| 3 | Density | kg/m^3 |  |
| 4 | Density | kg/m^3 | Y |

ID 1 would be a raw measurement with the SWE tube  
ID 2 would be a spatial SWE raster value (could argue that that is derived)
ID 3 is again a raw measurement
ID 4 is the derived SWE from a profile

Think we would unnecessarily create records for entries that are only different by date. That is easiest kept at the Point/Layer data table as it belongs there. Also thinking of GPR measurements or depth transects, those would have to have thousands of entries that are identical when kept in the measurement table.

@micah-prime @micahjohnson150 - Thoughts?

**Comment by aaarendt** [comment]
@jomey there is an existing "measurements" table. Can you remind me, are we expanding that with columns you specify above, or creating a separate table?

**Comment by jomey** [comment]
That is the one. We should probably log an issue to rename the table to reflect that class

**Comment by jomey** [comment]
Going of the example I posted, some times the SnowEx data can have a values that was derived from others. This column will give us a chance to add a new entry for those types and indicate to the user that this is not a raw measurement type, but something that was derived from other date in the DB. 
A bulk snow density of instance is one example for a snow pit.

**Comment by aaarendt** [comment]
That makes sense and I agree. I think our wires might be crossing around your use of the term "composite", which I understood to mean [composite column type](https://docs.sqlalchemy.org/en/20/orm/composites.html#sqlalchemy.orm.composite). 

Right now I'm just going to create a variable called derived of type Boolean.

**Comment by jomey** [comment]
> That makes sense and I agree. I think our wires might be crossing around your use of the term "composite", which I understood to mean [composite column type](https://docs.sqlalchemy.org/en/20/orm/composites.html#sqlalchemy.orm.composite).
> 
> Right now I'm just going to create a variable called derived of type Boolean.

Apologies about the confusion and I forgot the ambiguous terminology.
The different column name sounds great!
