### ISSUE TITLE
Column: Date Accessed - Needed in Base?

### ISSUE THREAD

**Issue by jomey** [SnowEx/snowexsql#143]
Do we need the `date_accessed` column in all the tables?

It seems to indicate when a database record was created. With the new schema it seems that we don't need that with all tables. The DOI would serve as a unique identifier and it seems the only place we would need 'date_accessed' as the date when it was imported.

Maybe this is also the opportunity to rename this column to something more descriptive such as 'imported_date'?

CC: @micah-prime @micahjohnson150

**Comment by micah-prime** [comment]
Agreed, I think that makes more sense. Originally we had talked about just getting rid of this column, but it could be helpful for citations if we left it in the DOI table

**Comment by micahjohnson150** [comment]
The goal of this was so that someone could recreate the nsidc citation so the date is the date we pulled it from the nsidc. Not sure if that's useful now that folks have decided to cite the database doi.
