### ISSUE TITLE
Add HRRR data to the DB

### ISSUE THREAD

**Issue by micahjohnson150** [SnowEx/snowexsql#15]
HP asked for the HRRR data over GM to be uploaded. 

@hpmarshall do you know what variables you want?

**Comment by hpmarshall** [comment]
1) Temp
2) Precip
3) RH

If there is wind speed and/or direction, that would be super helpful too.

Thanks!
HP

-------------------------------------------------
Hans-Peter Marshall, Associate Professor
Cryosphere Geophysics And Remote Sensing (CryoGARS)
Department of Geosciences, Boise State University
1910 University Dr., ERB 3155
Boise, ID 83725-1536
http://earth.boisestate.edu/cryogars
Twitter: @snowradar
hpmarshall@boisestate.edu
(208) 426-1416 (o)
(208) 426-4061 (f)

**Comment by micahjohnson150** [comment]
Wind is in there too s. 

Since the HRRR is a forecast product the 0th hour for precip is always 0s. Are you ok with the 1st forecast hour being the precip? 

Also what is the exact date range you are looking for? Just the dates that data was collected out there?  All the hours/days in between?

**Comment by hpmarshall** [comment]
Thanks Micah.

I thought HRRR is a reanalysis product?  I think we want whatever would be
the best precip estimate...i.e. what you guys were using to drive iSnobal.

For the time range, we would want every hour from Oct 1 onwards (water
year) until the date of the last flight, so say Feb 15.

-HP






-------------------------------------------------
Hans-Peter Marshall, Associate Professor
Cryosphere Geophysics And Remote Sensing (CryoGARS)
Department of Geosciences, Boise State University
1910 University Dr., ERB 3155
Boise, ID 83725-1536
http://earth.boisestate.edu/cryogars
Twitter: @snowradar
hpmarshall@boisestate.edu
(208) 426-1416 (o)
(208) 426-4061 (f)

**Comment by micahjohnson150** [comment]
we used the 1st hour which is the only reason I know this haha. 

It is a reanalysis product but for every hour there are 15 forecast hours. 

Ok I will download 10-1 to 02-15.  Do we want to crop them to the respective areas?

**Comment by hpmarshall** [comment]
The HRRR data will be valuable over the entire UAVSAR flight boxes, so you
can trim to that.

Thanks!
HP

-------------------------------------------------
Hans-Peter Marshall, Associate Professor
Cryosphere Geophysics And Remote Sensing (CryoGARS)
Department of Geosciences, Boise State University
1910 University Dr., ERB 3155
Boise, ID 83725-1536
http://earth.boisestate.edu/cryogars
Twitter: @snowradar
hpmarshall@boisestate.edu
(208) 426-1416 (o)
(208) 426-4061 (f)
