### ISSUE TITLE
Add more abstracted functions/tools  to make accessing  data easier

### ISSUE THREAD

**Issue by micahjohnson150** [SnowEx/snowexsql#21]
It was concluded yesterday during the sprint meeting for hack week that having more tools for extracting a dataset from the db into a file might be very helpful. 
I am thinking:

1. Download a raster to file with a shapefile to crop
2. Download Points that land in a shapefile

**Comment by jomey** [comment]
@micahjohnson150 - Sounds like this is complete?

**Comment by micahjohnson150** [comment]
Oh yeah super dun!
