### ISSUE TITLE
Adding 2020 SnowEx Snow Depth from Snow Poles Dataset

### ISSUE THREAD

**Issue by catherine-m-breen** [SnowEx/snowexsql#36]
Please add the 2020 SnowEx SnowDepth from Snow Poles Dataset. The .csv file will be emailed separately.

**Comment by micahjohnson150** [comment]
@catherine-m-breen is the time in the CSV in Mountain Standard Time?

**Comment by catherine-m-breen** [comment]
> @catherine-m-breen is the time in the CSV in Mountain Standard Time?

Yes, it is in Mountain Standard Time.

**Comment by micahjohnson150** [comment]
@catherine-m-breen Could you double check your column names in the csv? 

```
Camera,Date&Time,Longitude,Latitude,UTM WGS84 Northing (meters),UTM WGS84 Easting (meters),Depth (cm)
W1B,9/29/2019 11:00,39.008078,-108.184794,4321444.155,743766.4795,0.00124
```
This gets mapped like below:
```
Camera                                     W1B
Date&Time                      9/29/2019 11:00
Longitude                            39.008078
Latitude                           -108.184794
UTM WGS84 Northing (meters)        4321444.155
UTM WGS84 Easting (meters)         743766.4795
Depth (cm)                             0.00124
```
I think the lat/long column names are flipped.

**Comment by micahjohnson150** [comment]
Also we need a short name for the instrument so it is easier to filter. There is multiple depths datasets so we will want distinguish it easier.  Here are some ideas.

* camera_derived or photo_derived 
* camera_trap 

A query in python to access the entire dataset would then look something like:
``` python
# Return all columns of the the table
qry = session.query(PointData)

# Filter Point data to just data collected via thecamera dataset
qry.filter(PointData.instrument=='camera_derived')

# Request Data 
results = qry.all()
```

**Comment by catherine-m-breen** [comment]
Good call, Micah! I like camera_trap or camera_derived. Let's go with 'camera-trap'
