### ISSUE TITLE
Adding other GPR datasets

### ISSUE THREAD

**Issue by 4rwebb** [SnowEx/snowexsql#63]
Hi Micahs,

I think it would be great to also add the CSU and UNM GPR datasets. These are really complementary with Tate's BSU dataset. Links below.

https://nsidc.org/data/SNEX20_GM_CSU_GPR/versions/1

https://nsidc.org/data/SNEX20_UNM_GPR/versions/1

Thanks!
Ryan

**Comment by micahjohnson150** [comment]
Data management and building is now held in the snowex_db. Please follow this issue migrated to https://github.com/SnowEx/snowex_db/issues/2
