### ISSUE TITLE
Add Snow Classification data set (Sturm & Liston, 2021)

### ISSUE THREAD

**Issue by meganmason** [SnowEx/snowexsql#69]
NSIDC data set: https://nsidc.org/data/NSIDC-0768/versions/1 ([link](https://nsidc.org/data/NSIDC-0768/versions/1))

This data set consists of global, seasonal snow classifications determined from air temperature,
precipitation, and wind speed climatologies. The classifications represent a climatological average
for the 39 year period from 1981–2019. 

Specifically for the snowexsql database, I recommend adding the North American downscaled rasters (tiffs, netCDF, and/or ascii) files at 300m, 1km, 5km, and 50km (see the NSIDC User's Guide for detail). The snow classifications (tundra, prairie, montane forest, ephemeral, etc.) will help users filter data from multiple SnowEx campaigns where the objectives were to study snow in different snow climate types. 

The associated paper citation for this data set is Sturm, M., & Liston, G. E. (2021). Revisiting the global seasonal snow classification: An updated dataset for earth system applications. Journal of Hydrometeorology, 22(11), 2917-2938.

**Comment by micahjohnson150** [comment]
Hey @meganmason I should have mentioned these will all live now at the snowex_db repo. I added it there and I am linking them. 

Migrated to [snowex_db #5](https://github.com/SnowEx/snowex_db/issues/5)

**Comment by micahjohnson150** [comment]
@meganmason if you go comment on the snowex_db version of this issue it will keep you updated when I mess with it.
