### ISSUE TITLE
get_db dependency issue

### ISSUE THREAD

**Issue by ahmadhojati** [SnowEx/snowexsql#77]
I have issues with **get_db**. See below

![db_error](https://user-images.githubusercontent.com/46757659/222214613-e0b9fbda-34df-4561-af05-f21b0a569ec1.png)

Here is the **pip freeze** results:

[pip_freeze.pdf](https://github.com/SnowEx/snowexsql/files/10863840/pip_freeze.pdf)

**Comment by jomey** [comment]
@micahjohnson150 - #78 fully addressed this, no?

**Comment by micahjohnson150** [comment]
@jomey yep!  I tried to comment in the PR to close it but it was obviously a swing and a miss. lol
