### ISSUE TITLE
Create more coummunity guides

### ISSUE THREAD

**Issue by jomey** [SnowEx/snowexsql#88]
* [CONTRIBUTING](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
* [CODE of CONDUCT](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)

**Comment by jomey** [comment]
@micah-prime pointed to a great contributors guide in Metloom to adapt
https://github.com/M3Works/metloom/blob/main/CONTRIBUTING.rst

**Comment by aaarendt** [comment]
Here's another contributor guide we could consider, from icepyx:
https://github.com/icesat2py/icepyx/blob/development/doc/source/contributing/contribution_guidelines.rst
