### ISSUE TITLE
Add package to conda-forge

### ISSUE THREAD

**Issue by scottyhq** [SnowEx/snowexsql#93]
**Is your feature request related to a problem? Please describe.**

Adding snowexsql to conda-forge would facilitate installing with conda/mamba and integrating into larger environment (e.g. https://github.com/CryoInTheCloud/hub-image/blob/main/environment.yml). While it's possible to mix conda and pip, usually the dependency solving is independent, which can lead to complications.

**Describe the solution you'd like**

```
mamba install snowexsql
```

** Additional info**

Since snowexsql is already released on pip, there are tools to mostly automate the process of generating the recipe and syncing releases https://conda-forge.org/docs/maintainer/adding_pkgs/

**Comment by micah-prime** [comment]
Thanks @scottyhq ! I will take care of this

**Comment by micah-prime** [comment]
Hopefully I'm doing this right (I've been a pypi purist for a while 😆 )

https://github.com/conda-forge/staged-recipes/pull/27104

**Comment by micah-prime** [comment]
@scottyhq snowexsql is available on conda-forge. https://anaconda.org/conda-forge/snowexsql

I'm going to close this issue, but let me know if there is anything else that needs to happen on that front
