### ISSUE TITLE
Add a derived flag to db?

### ISSUE THREAD

**Issue by micahjohnson150** [SnowEx/snowexsql#94]
**Is your feature request related to a problem? Please describe.**
Some data that may go into the db may end up being a derived form of other data in the db. It would be nice to know when thats the case. 

Ex. SWE summary file is in the point db (soon) and is derived from the density files 

**Describe the solution you'd like**
I think the best solution is a boolean column that adds if the product is derived or not.

This was discussed with @micah-prime @jomey @aaarendt  today during our meeting.

**Comment by jomey** [comment]
Should this be a [DB repo](https://github.com/SnowEx/snowex_db) issue?

**Comment by jomey** [comment]
Logging some discussions thoughts:
The new DB structure will introduce a table called 'Measurement Types'. The thought was that we could create a record there indicating a "real" measurement or a "composite". This could also accommodate this use case.
