### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by jomey** [SnowEx/snowexsql#95]
Stumbled on this when looking at the effort of @micah-prime to create a conda release (#93)

I propose to change the library license to GNU v3 (https://choosealicense.com/licenses/gpl-3.0/)

Reason:
The current copyright of Copyright "2021 (c) Boise State University SnowEx Hackweek" seems appropriate for the version(s) released back then, but I would like to shift to a more community and open effort.

Any objections or thoughts?
@micahjohnson150 @aaarendt

**Comment by hpmarshall** [comment]
Makes a lot of sense to me.

**Comment by micah-prime** [comment]
Good call - I think changing the license makes a lot of sense. 
I am a fan of the MIT license https://choosealicense.com/licenses/mit/ generally because I think the "copy left" GNU licenses are likely to be ignored by most folks anyway.

**Comment by jomey** [comment]
> I am a fan of the MIT license https://choosealicense.com/licenses/mit/ generally because I think the "copy left" GNU licenses are likely to be ignored by most folks anyway.

Agreed that it is a simpler license and most people won't read it anyways. Reason I am advocating for GNU is that we could at least try to have them keep the same license and state the changes. As you said though, this is probably a pipe dream.

You OK with giving GNU a shot?

**Comment by aaarendt** [comment]
This works for me considering no others have contributed yet. Seems the right time to make a change.
